// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Palesteeny_Project.Models;

#nullable disable

namespace Palesteeny_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250704200907_Palesteeny1")]
    partial class Palesteeny1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Palesteeny_Project.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Climate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Food")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageClimate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNameMeaning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameMeaning")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.Drawing", b =>
                {
                    b.Property<int>("DrawingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrawingId"));

                    b.Property<string>("BrushType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("UserPalId")
                        .HasColumnType("int");

                    b.HasKey("DrawingId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserPalId");

                    b.ToTable("Drawings");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.FavoriteStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QusiId")
                        .HasColumnType("int");

                    b.Property<int>("UserPalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QusiId");

                    b.HasIndex("UserPalId");

                    b.ToTable("FavoriteStories");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.Qusi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Qusis");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.QusiImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("QusiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QusiId");

                    b.ToTable("QusiImages");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.StoryBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastImageIndex")
                        .HasColumnType("int");

                    b.Property<int>("QusiId")
                        .HasColumnType("int");

                    b.Property<int>("UserPalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QusiId");

                    b.HasIndex("UserPalId");

                    b.ToTable("StoryBookmarks");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.UserPal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersPal");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.Drawing", b =>
                {
                    b.HasOne("Palesteeny_Project.Models.Template", "Template")
                        .WithMany("Drawings")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Palesteeny_Project.Models.UserPal", "User")
                        .WithMany("Drawings")
                        .HasForeignKey("UserPalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.FavoriteStory", b =>
                {
                    b.HasOne("Palesteeny_Project.Models.Qusi", "Qusi")
                        .WithMany()
                        .HasForeignKey("QusiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palesteeny_Project.Models.UserPal", "User")
                        .WithMany("FavoriteStories")
                        .HasForeignKey("UserPalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qusi");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.QusiImage", b =>
                {
                    b.HasOne("Palesteeny_Project.Models.Qusi", "Qusi")
                        .WithMany("Images")
                        .HasForeignKey("QusiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qusi");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.StoryBookmark", b =>
                {
                    b.HasOne("Palesteeny_Project.Models.Qusi", "Qusi")
                        .WithMany()
                        .HasForeignKey("QusiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palesteeny_Project.Models.UserPal", "User")
                        .WithMany("StoryBookmarks")
                        .HasForeignKey("UserPalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qusi");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.Qusi", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.Template", b =>
                {
                    b.Navigation("Drawings");
                });

            modelBuilder.Entity("Palesteeny_Project.Models.UserPal", b =>
                {
                    b.Navigation("Drawings");

                    b.Navigation("FavoriteStories");

                    b.Navigation("StoryBookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
